routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\App;

Route::get('/', function () {
    return redirect()->route('presupuestos.listado');
});

Route::middleware('auth')
    ->namespace('Admin\\')
    ->group(function () {

//        Route::get('refresh-csrf', function(){
//            session()->regenerate();
//            return csrf_token();
//        })->name('refresh_token');

        //USUARIOS
        Route::get('usuarios', 'UsuarioController@listado')->name('usuarios.listado');
        Route::post('usuarios','UsuarioController@guardar')->name('usuarios.guardar');
        Route::get('usuarios/{user}/editar', 'UsuarioController@editar')->name('usuarios.editar');
        Route::put('usuarios/{user}', 'UsuarioController@actualizar')->name('usuarios.actualizar');

        //CLIENTES
        Route::get('clientes', 'ClienteController@listado')->name('clientes.listado');
        Route::post('clientes','ClienteController@guardar')->name('clientes.guardar');
        Route::get('clientes/{cliente}/editar', 'ClienteController@editar')->name('clientes.editar');
        Route::put('clientes/{cliente}', 'ClienteController@actualizar')->name('clientes.actualizar');
        Route::get('clientes/getClientesJson', 'ClienteController@getClientesJson')->name('clientes.getClientesJson');

        //PRODUCTOS
        Route::get('productos', 'ProductoController@listado')->name('productos.listado');
        Route::post('productos','ProductoController@guardar')->name('productos.guardar');
        Route::get('productos/{producto}/editar', 'ProductoController@editar')->name('productos.editar');
        Route::put('productos/{producto}', 'ProductoController@actualizar')->name('productos.actualizar');
        Route::get('productos/getProductosJson', 'ProductoController@getProductosJson')->name('productos.getClientesJson');

        //MARCAS
        Route::get('marcas/{nombre?}', 'MarcaController@guardar')->name('marcas.guardar');

        // PRESUPUESTOS
        Route::get('presupuestos', 'PresupuestoController@listado')->name('presupuestos.listado');
        Route::get('presupuestos/nuevo', 'PresupuestoController@crear')->name('presupuestos.crear');
        Route::post('presupuestos', 'PresupuestoController@guardar')->name('presupuestos.guardar');
        Route::get('presupuestos/{presupuesto}', 'PresupuestoController@ver')->name('presupuestos.ver');
        Route::get('presupuestos/{presupuesto}/editar', 'PresupuestoController@editar')->name('presupuestos.editar');
        Route::get('presupuestos/{presupuesto}/pdf', 'PresupuestoController@presupuesto')->name('presupuestos.verPdf');
        Route::post('presupuestos/{presupuesto}/enviar', 'PresupuestoController@enviarPdf')->name('presupuestos.enviarPdf');
    });


Auth::routes(['register' => false]);

app/Presupuesto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Presupuesto extends Model
{
    protected $table = 'presupuestos';
    protected $guarded = [];

    public function cliente()
    {
        return $this->belongsTo(Cliente::class, 'cliente_id');
    }

    public function productos()
    {
        return $this->belongsToMany(Producto::class, 'presupuesto_producto',
            'presupuesto_id', 'producto_id')
            ->using(PresupuestoProducto::class)
            ->withPivot('presupuesto_id','producto_id','moneda_id', 'cantidad', 'precio_unitario', 'subtotal');
    }

    public function usuario()
    {
        return $this->belongsTo(User::class, 'usuario_id');
    }

    public function moneda()
    {
        return $this->belongsTo(Moneda::class, 'moneda_id');
    }

    public function sucursal()
    {
        return $this->belongsTo(Sucursal::class, 'sucursal_id');
    }

    public function empresa()
    {
        return $this->belongsTo(Empresa::class, 'empresa_id');
    }


    public function formas_pago()
    {
        return $this->belongsToMany(FormaDePago::class, 'forma_pago_presupuesto',
            'presupuesto_id', 'forma_pago_id')
            ->using(FormaPagoPrespuesto::class)
            ->withPivot('moneda_id', 'monto', 'fecha');
    }


    /**
     * ACCESSORS AND MUTATORS
     */
    public function getMontoTotalAttribute()
    {
        return $this->moneda->simbolo ." ". number_format($this->monto,2, ",", ".");
    }

    public function getNroCotizacionAttribute()
    {
        return str_pad($this->id, 10, "0", STR_PAD_LEFT);
    }

    public function getProductosAsociadosAttribute()
    {
        $nombres = [];
        foreach ($this->productos as $producto) {
            $nombres[] = $producto->producto_completo;
        }

        return implode(", ", $nombres);
    }
}

app/Http/Controllers/Admin/PresupuestoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Empresa;
use App\FormaDePago;
use App\FormaPagoPrespuesto;
use App\Http\Controllers\Controller;
use App\Marca;
use App\Moneda;
use App\Notifications\EnviarPresupuesto;
use App\Presupuesto;
use App\PresupuestoProducto;
use App\Sucursal;
use Barryvdh\DomPDF\Facade;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Notification;

class PresupuestoController extends Controller
{
    public function listado(Request $request)
    {
        $presupuestos = Presupuesto::with("cliente", "productos")
            ->orderBy('created_at','DESC')
            ->paginate(20);

        return view('presupuestos.listado', compact('presupuestos'));
    }

    public function crear()
    {
        $monedas = Moneda::all();
        $formasPago = FormaDePago::all();
        $marcas = Marca::orderBy('nombre')->get();
        $sucursales = Empresa::all();

        return view('presupuestos.crear', compact('monedas', 'formasPago', 'marcas', 'sucursales'));
    }

    public function guardar(Request $request)
    {
        DB::beginTransaction();
        try {
            $pagos = collect($request->only('pagos')["pagos"]);

            $productos = $request->input('producto');

            $dataPresupuesto = $request->input('presupuesto');
            $dataPresupuesto["usuario_id"] = auth()->user()->id;
            $dataPresupuesto["monto"] = $productos["total"];
            unset($productos["total"]);
            $dataPresupuesto["sucursal_id"] = auth()->user()->sucursal->id;

            $presupuesto = Presupuesto::create($dataPresupuesto);

            $presupuesto->productos()->attach($productos);

            $presupuesto->formas_pago()->attach($pagos->toArray());

            DB::commit();
        }catch (\Exception $e) {
            DB::rollBack();
            return back()->withErrors($e->getMessage());
        }
        return redirect()->route("presupuestos.ver", $presupuesto)->with("success", "El presupuesto se creo con éxito");
    }

    public function ver(Presupuesto $presupuesto)
    {
        $presupuesto->load("cliente", "productos", "moneda");

        return view('presupuestos.ver', compact('presupuesto'));
    }

    public function editar(Presupuesto $presupuesto)
    {
        $monedas = Moneda::all();
        $formasPago = FormaDePago::all();
        $marcas = Marca::orderBy('nombre')->get();
        $presupuesto->load("cliente", "productos", "moneda");
        $otrasFormasPago = $presupuesto->formas_pago->where("id", "!=",3)->values();
        $cheques = $presupuesto->formas_pago->where("id", 3)->values();
        $sucursales = Empresa::all();

        return view('presupuestos.editar', compact('monedas', 'formasPago', 'marcas',
            'presupuesto','cheques', 'otrasFormasPago', 'sucursales'));
    }

    public function presupuesto(Presupuesto $presupuesto)
    {
        $pdf = $this->getPdf($presupuesto);

        return $pdf->stream('presupuesto.pdf');
    }

    public function enviarPdf(Presupuesto $presupuesto, Request $request)
    {
        $pdf = $this->getPdf($presupuesto);

        $data = $request->all();
        try {
            Mail::send([], [], function ($email) use ($pdf, $data) {
                $email->from(auth()->user()->email);
                $email->to($data["email"]);
                $email->subject("Presupuesto");
                $email->setBody('Adjuntamos prespuesto requerido');
                $email->setBody('Saludos!');
                $email->attachData($pdf->output(), "presupusto.pdf");
            });
        }catch (\Exception $e) {
            return back()->withErrors($e->getMessage());
        }

        return back()->with("success", "El correo fue enviado");
    }

    private function getPdf(Presupuesto $presupuesto)
    {
        $presupuesto->load("cliente", "productos", "moneda");

        $vista = view('presupuestos.template.presupuesto', compact('presupuesto'))->render();

        return Facade::loadHtml($vista);
    }
}

resources/views/presupuestos/listado.blade.php
@extends('layouts.master')
@section('titulo', 'Listado de presupuestos')
@section('contenido')

    @include('partials.errors')
    @include('partials.success')
    <div class="row mb-4">
        <div class="col">
            <a href="{{ route('presupuestos.crear') }}" class="btn btn-primary btn-icon-split">
                <span class="icon text-white-50">
                    <i class="fas fa-plus"></i>
                </span>
                <span class="text">Nuevo presupuesto</span>
            </a>

        </div>
        <div class="col-md-3">
            <form action="{{ route('presupuestos.listado') }}" method="GET" id="buscarPresupuestoForm">
                <div class="input-group">
                    <input type="text" class="form-control" value="{{ request('buscar') }}" name="buscar" id="buscarPresupuesto"
                           placeholder="Buscar cliente por razón social o cuit">
                    <div class="input-group-append">
                        <a class="btn btn-primary" href="{{ route('clientes.listado') }}" title="Limpiar resultados">
                            <i class="fas fa-broom"></i>
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-striped">
            <thead class="thead-dark">
            <th>Nro</th>
            <th>Cliente</th>
            <th>Producto</th>

            <th>Importe</th>
            <th>Acción</th>
            </thead>
            <tbody>
            @forelse($presupuestos as $presupuesto)
                <tr>
                    <td>{{ $presupuesto->id }}</td>
                    <td>{{ $presupuesto->cliente->razon_social }}</td>
                    <td>{{ $presupuesto->productos_asociados }}</td>
                    <td>{{ number_format($presupuesto->monto, 2, ",", ".")}} </td>
                    <td>
                        <a href="{{ route('presupuestos.editar', $presupuesto) }}" class="btn btn-info btn-circle btn-sm editar cursor" title="Información">
                            <i class="fas fa-edit"></i>
                        </a>

                        <a href="{{ route('presupuestos.ver', $presupuesto) }}" class="btn btn-success btn-circle btn-sm editar cursor" title="Reenviar">
                            <i class="fas fa-envelope"></i>
                        </a>
                    </td>
                </tr>
            @empty
                <td colspan="5">No se encontraron resultados</td>
            @endforelse
            </tbody>
        </table>

        {{ $presupuestos->appends([
            'buscar' => request('buscar')
        ])->links() }}
    </div>
@endsection

resources/views/presupuestos/ver.blade.php
@extends('layouts.master')
@section('titulo', "Cotizacion Nº ".$presupuesto->id)
@section('contenido')
    @include('partials.errors')
    @include('partials.success')
    <style>
        img {
            display: block;
            max-width:320px;
            max-height:180px;
            width: auto;
            height: auto;
        }
    </style>

    <div class="row mb-4">
        <div class="col col-12">
            <a href="{{ route('presupuestos.verPdf', $presupuesto) }}" target="_blank" class="btn btn-success btn-icon-split" >
                    <span class="icon text-white-50">
                        <i class="fas fa-print"></i>
                    </span>
                <span class="text">Imprimir</span>
            </a>

            <button class="btn btn-info btn-icon-split" data-toggle="modal" data-target="#enviarPresupuesto">
                    <span class="icon text-white-50">
                        <i class="fas fa-envelope"></i>
                    </span>
                <span class="text">Enviar por correo</span>
            </button>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Cliente</h6>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-sm-3 col-12">
                            <p class="text-uppercase"><b>Razon social: </b>{{ $presupuesto->cliente->razon_social }}</p>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-12">
                            <p class="text-uppercase"><b>Correo: </b>{{ $presupuesto->cliente->email }}</p>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-12">
                            <p class="text-uppercase"><b>Teléfono: </b>{{ $presupuesto->cliente->telefono }}</p>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-12">
                            <p class="text-uppercase"><b>Cuit: </b>{{ $presupuesto->cliente->cuit }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Productos</h6>
                </div>
                <div class="card-body">
                    @foreach($presupuesto->productos as $producto)
                        <div class="row mb-4 pb-3" @if(!$loop->last) style="border-bottom: 1px solid #ebecf0" @endif>
                            <div class="col-lg-8 col-md-8 col-sm-8 col-12">
                                <p class="text-uppercase"><b>{{ $producto->producto_completo }}</b></p>
                                <p class="text-uppercase">
                                    <b>
                                        Precio: {{ $producto->pivot->cantidad }} X {{ $producto->pivot->moneda->simbolo }} {{ $producto->pivot->subtotal }}
                                    </b>
                                </p>
                                <p class="text-uppercase"><b>Descripción</b></p>
                                {!! $producto->descripcion !!}
                            </div>
                            <div class="col-lg-4 col-md-4 col-sm-4 col-12 text-center">
                                @if($producto->imagen()->exists())
                                    <img src="{{ asset('images/productos') }}/{{$producto->imagen->nombre}}" alt=""  >
                                @else
                                    <img src="{{ asset('images/Imagen-no-disponible.png') }}" alt="" class="img-fluid img-thumbnail">
                                @endif

                            </div>
                        </div>

                    @endforeach
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Condiciones comerciales</h6>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-sm-3 col-12">
                            <p class="text-uppercase"><b>Validez de la oferta: </b>{{ $presupuesto->validez }} dias</p>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-12">
                            <p class="text-uppercase"><b>IVA: </b>{{ $presupuesto->iva == 'con_iva' ? 'Incluye IVA' : 'No incluye IVA' }}</p>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-12">
                            <p class="text-uppercase"><b>Plazo de entrega: </b>{{ $presupuesto->plazo_entrega == 0 ? 'Inmediata' : $presupuesto->plazo_entrega .' dias' }}</p>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-12">
                            <p class="text-uppercase"><b>Flete: </b>{{ $presupuesto->flete }}</p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card shadow mb-4" style="min-height: 173px">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Forma de pago</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                            <th>Forma de pago</th>
                            <th>Monto</th>
                            <th>Fecha</th>
                            </thead>
                            <tbody>
                            @foreach($presupuesto->formas_pago as $formaPago)
                                <tr>
                                    <td>{{ $formaPago->nombre }}</td>
                                    <td>{{ optional($formaPago->pivot->moneda)->simbolo }} {{ number_format($formaPago->pivot->monto, 2, ",",".") }}</td>
                                    <td>{{ optional($formaPago->pivot->fecha)->format("d/m/Y") }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                            <tfoot>
                            <tr class="bg-danger text-white font-weight-bold" style="font-size: 1.6em">
                                <td>Total</td>
                                <td colspan="2">{{ number_format($presupuesto->monto, 2, ",",".") }}</td>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="enviarPresupuesto" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Enviar presupuesto</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ route('presupuestos.enviarPdf', $presupuesto) }}" method="POST">
                    @csrf
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="">Correo electrónico</label>
                            <input type="email" class="form-control" name="email" required value="{{ $presupuesto->cliente->email }}">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </form>

            </div>
        </div>
    </div>

@endsection