routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\App;

Route::get('/', function () {
    return redirect()->route('presupuestos.listado');
});

Route::middleware('auth')
    ->namespace('Admin\\')
    ->group(function () {

//        Route::get('refresh-csrf', function(){
//            session()->regenerate();
//            return csrf_token();
//        })->name('refresh_token');

        //USUARIOS
        Route::get('usuarios', 'UsuarioController@listado')->name('usuarios.listado');
        Route::post('usuarios','UsuarioController@guardar')->name('usuarios.guardar');
        Route::get('usuarios/{user}/editar', 'UsuarioController@editar')->name('usuarios.editar');
        Route::put('usuarios/{user}', 'UsuarioController@actualizar')->name('usuarios.actualizar');

        //CLIENTES
        Route::get('clientes', 'ClienteController@listado')->name('clientes.listado');
        Route::post('clientes','ClienteController@guardar')->name('clientes.guardar');
        Route::get('clientes/{cliente}/editar', 'ClienteController@editar')->name('clientes.editar');
        Route::put('clientes/{cliente}', 'ClienteController@actualizar')->name('clientes.actualizar');
        Route::get('clientes/getClientesJson', 'ClienteController@getClientesJson')->name('clientes.getClientesJson');

        //PRODUCTOS
        Route::get('productos', 'ProductoController@listado')->name('productos.listado');
        Route::post('productos','ProductoController@guardar')->name('productos.guardar');
        Route::get('productos/{producto}/editar', 'ProductoController@editar')->name('productos.editar');
        Route::put('productos/{producto}', 'ProductoController@actualizar')->name('productos.actualizar');
        Route::get('productos/getProductosJson', 'ProductoController@getProductosJson')->name('productos.getClientesJson');

        //MARCAS
        Route::get('marcas/{nombre?}', 'MarcaController@guardar')->name('marcas.guardar');

        // PRESUPUESTOS
        Route::get('presupuestos', 'PresupuestoController@listado')->name('presupuestos.listado');
        Route::get('presupuestos/nuevo', 'PresupuestoController@crear')->name('presupuestos.crear');
        Route::post('presupuestos', 'PresupuestoController@guardar')->name('presupuestos.guardar');
        Route::get('presupuestos/{presupuesto}', 'PresupuestoController@ver')->name('presupuestos.ver');
        Route::get('presupuestos/{presupuesto}/editar', 'PresupuestoController@editar')->name('presupuestos.editar');
        Route::get('presupuestos/{presupuesto}/pdf', 'PresupuestoController@presupuesto')->name('presupuestos.verPdf');
        Route::post('presupuestos/{presupuesto}/enviar', 'PresupuestoController@enviarPdf')->name('presupuestos.enviarPdf');
    });


Auth::routes(['register' => false]);

app/Producto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class Producto extends Model
{
    protected $table = 'productos';
    protected $guarded = [];

    /**
     * RELACIONES
     */
    public function marca()
    {
        return $this->belongsTo(Marca::class, 'marca_id');
    }

    public function imagen()
    {
        return $this->belongsTo(Imagen::class, 'imagen_id', 'id');
    }

    public function presupuestos()
    {
        return $this->belongsToMany(Presupuesto::class, 'presupuesto_producto',
            'producto_id', 'presupuesto_id')
            ->using(PresupuestoProducto::class)
            ->withPivot('moneda_id', 'precio');
    }
    /**
     * FIN RELACIONES
     */

    /**
     * SCOPES
     */
    public function scopeBuscar($query, Request $request)
    {
        return $query->where("nombre", "LIKE", "%{$request->buscar}%")
            ->orWhere(function ($q) use ($request) {
                $q->where("modelo", "LIKE", "%{$request->buscar}%");
            })->orWhereHas('marca', function ($q) use ($request){
                $q->where("nombre", $request->buscar);
            });
    }
    /**
     * END SCOPES
     */

    /**
     * ACCESSORS Y MUTATOS
     */
    public function getDescExcerptAttribute()
    {
        return Str::words($this->descripcion,5);
    }

    public function getProductoCompletoAttribute()
    {
        return strtoupper("{$this->nombre} Modelo {$this->modelo} {$this->marca->nombre}");
    }
}

app/Http/Controllers/Admin/ProductoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\ProductoRequest;
use App\Imagen;
use App\Marca;
use App\Producto;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductoController extends Controller
{
    public function listado(Request $request)
    {
        $productos = Producto::with('marca')
            ->buscar($request)
            ->orderBy("nombre")
            ->orderBy('marca_id')
            ->paginate(20);

        $marcas = Marca::all();

        return view('productos.listado', compact('productos', 'marcas'));
    }

    public function guardar(ProductoRequest $request)
    {
        DB::beginTransaction();
        try {
            $imagen = null;
            if ($request->hasFile('imagen')) {
                $imagen = $this->guardarImagen($request);
            }

            $producto = Producto::create([
                "nombre" => $request->nombre,
                "modelo" => $request->modelo,
                "descripcion" => $request->descripcion,
                "marca_id" => $request->marca_id,
                "imagen_id" => optional($imagen)->id
            ]);

            DB::commit();
        }catch (\Exception $ex) {
            DB::rollBack();
            if ($request->ajax()) {
                return response()->json(["data" => $ex->getMessage()], 500);
            }
            return back()->withErrors($ex->getMessage());
        }

        if ($request->ajax()) {
            return response()->json(["data" => $producto], 200);
        }
        return back()->with('success', 'El producto se creo con éxito');
    }

    private function guardarImagen(Request $request)
    {
        $image = $request->imagen;

        $extension = $image->getClientOriginalExtension();

        $filenametostore = time(). '.' . $extension;

        $image->move(public_path('images/productos/'),$filenametostore);

        return Imagen::create([
            'url' => 'public/images/productos/' . $filenametostore,
            'nombre' => $filenametostore,
            'mime' => $image->getClientMimeType(),
            'alt' => $request->nombre,
            'extension' => $extension,
            'descripcion' => strip_tags($request->descripcion)
        ]);
    }

    public function editar(Producto $producto)
    {
        $producto->load('marca', 'imagen');

        $marcas = Marca::all();

        return view('productos.editar', compact('producto', 'marcas'));
    }

    public function actualizar(ProductoRequest $request, Producto $producto)
    {
        DB::beginTransaction();
        try {
            $data = $request->except(['imagen']);

            $producto->fill($data);

            if ($request->hasFile('imagen')) {
                $producto->imagen()->dissociate();
                $producto->imagen()
                    ->associate($this->guardarImagen($request))
                    ->save();
            }
            $producto->save();
            DB::commit();
        }catch (\Exception $ex) {
            DB::rollBack();
            return redirect()->route('productos.editar', $producto)->withErrors($ex->getMessage());

        }

        return redirect()->route('productos.editar', $producto)->with('success', 'El producto se modificó con éxito');
    }

    public function getProductosJson()
    {
        return Producto::select('productos.id', DB::raw("CONCAT('Nombre: ',productos.nombre, ' - Modelo: ', modelo, ' - Marca: ', marcas.nombre) AS value"))
            ->join("marcas", "productos.marca_id", "=", "marcas.id")
            ->where("productos.nombre", "LIKE", "%{$_GET['term']}%")
            ->orWhere('modelo', "LIKE", "%{$_GET['term']}%")
            ->get()
            ->toJson();
    }
}

resources/views/productos/editar.blade.php
@extends('layouts.master')
@section('titulo', 'Editar producto')
@section('contenido')
    <style>
        img {
            display: block;
            max-width:320px;
            max-height:180px;
            width: auto;
            height: auto;
        }
    </style>
    <div class="row">
        <div class="col-12">
            @include('partials.errors')
            @include('partials.success')
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary text-capitalize">{{ $producto->nombre }} {{ $producto->modelo }}</h6>
                </div>
                <div class="card-body">
                    <form id="editarProductoForm" action="{{ route('productos.actualizar', $producto) }}" method="POST" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="form-row">
                            <div class="col-lg-4 col-md-4 col-sm-4 col-12">
                                <div class="form-group">
                                    <input type="text" class="form-control" required id="nombre" name="nombre" placeholder="Nombre" value="{{ $producto->nombre }}">
                                </div>
                            </div>

                            <div class="col-lg-4 col-md-4 col-sm-4 col-12">
                                <div class="form-group">
                                    <input type="text" class="form-control" required id="modelo" name="modelo" placeholder="Modelo" value="{{ $producto->modelo }}">
                                </div>
                            </div>

                            <div class="col-lg-4 col-md-4 col-sm-4 col-12">
                                <div class="form-group">
                                    <select name="marca_id" id="marca_id" required class="form-control">
                                        <option selected disabled>Seleccione la marca</option>
                                        @foreach($marcas as $marca)
                                            <option value="{{ $marca->id }}" @if($marca->id == $producto->marca->id) selected @endif>{{ ucfirst($marca->nombre) }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="input-group mb-3">
                                    <div class="custom-file">
                                        <input type="file" name="imagen" accept=".png, .jpg, .jpeg" class="custom-file-input" id="imagen">
                                        <label class="custom-file-label" for="imagen" aria-describedby="inputGroupFileAddon02">{{ !is_null($producto->imagen_id) ? $producto->imagen->nombre : "Seleccionar imagen" }}</label>
                                    </div>
                                    <div class="input-group-append">
                                        <span class="input-group-text" id="inputGroupFileAddon02"><i class="fas fa-cloud-upload-alt"></i> Subir</span>
                                    </div>
                                </div>

                                @if(!is_null($producto->imagen_id))
                                    <img id="imagenProducto" src="{{ asset("images/productos/".$producto->imagen->nombre) }}" class="img-fluid img-thumbnail">
                                @else
                                    <img id="imagenProducto" src="" alt="">
                                @endif

                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="form-group">
                                    <textarea name="descripcion" required id="descripcion" cols="30" rows="10"></textarea>
                                </div>
                            </div>
                        </div>


                        <div class="form-row mt-3">
                            <div class="col-12 text-center">
                                <button type="submit" id="enviar" class="btn btn-primary btn-block">Guardar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection
@section('js')
    <script src="{{ asset('tinymce/tinymce.js') }}"></script>
    <script>
        $(function () {
            let descripcion = @json($producto->descripcion);
            tinymce.init({
                selector: '#descripcion',
                language: 'es',
                init_instance_callback: function(editor) {
                    editor.setContent(descripcion, {format: 'html'});
                }
            });

            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        $('#imagenProducto').attr('src', e.target.result);
                    }
                    reader.readAsDataURL(input.files[0]);
                }
            }

            $('.custom-file-input').on('change',function(e){
                let fileName = $("#imagen").get(0).files[0].name;
                let nextSibling = e.target.nextElementSibling;
                nextSibling.innerText = fileName;
                readURL(this);
            });

            $('#enviar').click(function (e) {
                e.preventDefault();
                $("#editarProductoForm").submit();
            })
        })
    </script>
@endsection

resources/views/productos/listado.blade.php
@extends('layouts.master')
@section('titulo', 'Listado de productos')
@section('contenido')
    <style>
        img {
            display: block;
            max-width:320px;
            max-height:180px;
            width: auto;
            height: auto;
        }
    </style>
    @include('partials.errors')
    @include('partials.success')
    <div class="row mb-4">
        <div class="col">
            <button class="btn btn-primary btn-icon-split"
                    data-toggle="modal" data-target="#crearProducto">
                    <span class="icon text-white-50">
                        <i class="fas fa-plus"></i>
                    </span>
                <span class="text">Nuevo producto</span>
            </button>

        </div>
        <div class="col-md-3">
            <form action="{{ route('productos.listado') }}" method="GET" id="buscarProductoForm">
                <div class="input-group">
                    <input type="text" class="form-control" value="{{ request('buscar') }}" name="buscar" id="buscarProducto"
                           placeholder="Buscar prod por nombre, modelo o marca">
                    <div class="input-group-append">
                        <a class="btn btn-primary" href="{{ route('productos.listado') }}" title="Limpiar resultados">
                            <i class="fas fa-broom"></i>
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-striped">
            <thead class="thead-dark">
            <th>Nombre</th>
            <th>Modelo</th>
            <th>Descripcion</th>
            <th>Marca</th>
            <th>Acción</th>
            </thead>
            <tbody>
            @forelse($productos as $producto)
                <tr>
                    <td>{{ $producto->nombre }}</td>
                    <td>{{ $producto->modelo }}</td>
                    <td>{{ strip_tags($producto->desc_excerpt) }}</td>
                    <td>{{ $producto->marca->nombre }} </td>
                    <td>
                        <a href="{{ route('productos.editar', $producto) }}" class="btn btn-warning btn-circle btn-sm editar cursor" title="Editar">
                            <i class="fas fa-pencil-alt"></i>
                        </a>
                    </td>
                </tr>
            @empty
                <td colspan="5">No se encontraron resultados</td>
            @endforelse
            </tbody>
        </table>

        <div class="modal fade bd-example-modal-lg" id="crearProducto" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
            <div class="modal-dialog modal-xl" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Crear producto</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form id="crearProductoForm" action="{{ route('productos.guardar') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="modal-body">
                            <div class="container-fluid">
                                @include('productos.partials.form-crear', ["marcas" => $marcas])
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                            <button type="submit" id="btn_submit" class="btn btn-primary">Guardar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="modal fade bd-example-modal-lg" id="crearMarcaModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
            <div class="modal-dialog modal-xl" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Crear marca</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="container-fluid">
                            <div class="form-group">
                                <label for="">Nombre</label>
                                <input type="text" class="form-control" name="nombre" id="nombreMarca">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <button type="submit" id="guardarMarca" disabled class="btn btn-primary">Guardar</button>
                    </div>
                </div>
            </div>
        </div>

        {{ $productos->appends([
            'buscar' => request('buscar')
        ])->links() }}
    </div>
@endsection
@section('js')
    <script>
        $(function () {
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        $('#imagenProducto').attr('src', e.target.result);
                    }
                    reader.readAsDataURL(input.files[0]);
                }
            }

            $('.custom-file-input').on('change',function(e){
                let fileName = $("#imagen").get(0).files[0].name;
                let nextSibling = e.target.nextElementSibling;
                nextSibling.innerText = fileName;
                if(this.files[0].size > 2097152){
                    alert("¡La imagen es demasiado pesada! Seleccione una imagen menor a 1MB.");
                    this.value = "";

                }
                readURL(this);
            });

            $("#btn_submit").on("click", function (e) {
                e.preventDefault();
                console.log("entra");
                $("#crearProductoForm").submit();
            });

            $('#crearMarca').on("click", function(e){
                e.preventDefault();
                console.log("entra")
                $('#crearProducto').modal('hide');
                $('#crearMarcaModal').modal('show');
            });

            $("#nombreMarca").on("keyup", function (e) {
                e.preventDefault();
                if ($(this).val() != '') {
                    $("#guardarMarca").prop("disabled", false);
                }else {
                    $("#guardarMarca").prop("disabled", true);
                }
            });

            $("#guardarMarca").on("click", function (e) {
                e.preventDefault();
                let nombre = $("#nombreMarca").val();
                let url = "{{ route('marcas.guardar') }}";

                $.ajax({
                    url: url,
                    method: 'GET',
                    dataType: "json",
                    data: {
                        nombre: nombre
                    }
                }).done(function (result) {
                    $("#marca_id").append('<option value="'+result.id+'">'+result.nombre+'</option>');
                    $('#crearMarcaModal').modal('hide');
                    $('#crearProducto').modal('show');
                }).fail(function (result) {
                    console.log(result);
                })
            });
        });

    </script>
@endsection