routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\App;

Route::get('/', function () {
    return redirect()->route('presupuestos.listado');
});

Route::middleware('auth')
    ->namespace('Admin\\')
    ->group(function () {

//        Route::get('refresh-csrf', function(){
//            session()->regenerate();
//            return csrf_token();
//        })->name('refresh_token');

        //USUARIOS
        Route::get('usuarios', 'UsuarioController@listado')->name('usuarios.listado');
        Route::post('usuarios','UsuarioController@guardar')->name('usuarios.guardar');
        Route::get('usuarios/{user}/editar', 'UsuarioController@editar')->name('usuarios.editar');
        Route::put('usuarios/{user}', 'UsuarioController@actualizar')->name('usuarios.actualizar');

        //CLIENTES
        Route::get('clientes', 'ClienteController@listado')->name('clientes.listado');
        Route::post('clientes','ClienteController@guardar')->name('clientes.guardar');
        Route::get('clientes/{cliente}/editar', 'ClienteController@editar')->name('clientes.editar');
        Route::put('clientes/{cliente}', 'ClienteController@actualizar')->name('clientes.actualizar');
        Route::get('clientes/getClientesJson', 'ClienteController@getClientesJson')->name('clientes.getClientesJson');

        //PRODUCTOS
        Route::get('productos', 'ProductoController@listado')->name('productos.listado');
        Route::post('productos','ProductoController@guardar')->name('productos.guardar');
        Route::get('productos/{producto}/editar', 'ProductoController@editar')->name('productos.editar');
        Route::put('productos/{producto}', 'ProductoController@actualizar')->name('productos.actualizar');
        Route::get('productos/getProductosJson', 'ProductoController@getProductosJson')->name('productos.getClientesJson');

        //MARCAS
        Route::get('marcas/{nombre?}', 'MarcaController@guardar')->name('marcas.guardar');

        // PRESUPUESTOS
        Route::get('presupuestos', 'PresupuestoController@listado')->name('presupuestos.listado');
        Route::get('presupuestos/nuevo', 'PresupuestoController@crear')->name('presupuestos.crear');
        Route::post('presupuestos', 'PresupuestoController@guardar')->name('presupuestos.guardar');
        Route::get('presupuestos/{presupuesto}', 'PresupuestoController@ver')->name('presupuestos.ver');
        Route::get('presupuestos/{presupuesto}/editar', 'PresupuestoController@editar')->name('presupuestos.editar');
        Route::get('presupuestos/{presupuesto}/pdf', 'PresupuestoController@presupuesto')->name('presupuestos.verPdf');
        Route::post('presupuestos/{presupuesto}/enviar', 'PresupuestoController@enviarPdf')->name('presupuestos.enviarPdf');
    });


Auth::routes(['register' => false]);

app/Presupuesto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Presupuesto extends Model
{
    protected $table = 'presupuestos';
    protected $guarded = [];

    public function cliente()
    {
        return $this->belongsTo(Cliente::class, 'cliente_id');
    }

    public function productos()
    {
        return $this->belongsToMany(Producto::class, 'presupuesto_producto',
            'presupuesto_id', 'producto_id')
            ->using(PresupuestoProducto::class)
            ->withPivot('presupuesto_id','producto_id','moneda_id', 'cantidad', 'precio_unitario', 'subtotal');
    }

    public function usuario()
    {
        return $this->belongsTo(User::class, 'usuario_id');
    }

    public function moneda()
    {
        return $this->belongsTo(Moneda::class, 'moneda_id');
    }

    public function sucursal()
    {
        return $this->belongsTo(Sucursal::class, 'sucursal_id');
    }

    public function empresa()
    {
        return $this->belongsTo(Empresa::class, 'empresa_id');
    }


    public function formas_pago()
    {
        return $this->belongsToMany(FormaDePago::class, 'forma_pago_presupuesto',
            'presupuesto_id', 'forma_pago_id')
            ->using(FormaPagoPrespuesto::class)
            ->withPivot('moneda_id', 'monto', 'fecha');
    }


    /**
     * ACCESSORS AND MUTATORS
     */
    public function getMontoTotalAttribute()
    {
        return $this->moneda->simbolo ." ". number_format($this->monto,2, ",", ".");
    }

    public function getNroCotizacionAttribute()
    {
        return str_pad($this->id, 10, "0", STR_PAD_LEFT);
    }

    public function getProductosAsociadosAttribute()
    {
        $nombres = [];
        foreach ($this->productos as $producto) {
            $nombres[] = $producto->producto_completo;
        }

        return implode(", ", $nombres);
    }
}

app/User.php
<?php

namespace App;

use App\Notifications\ResetPassword;
use Illuminate\Http\Request;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Silber\Bouncer\Database\HasRolesAndAbilities;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRolesAndAbilities;

    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function sucursal()
    {
        return $this->belongsTo(Sucursal::class, 'sucursal_id');
    }
    /**
     * SCOPES
     */
    public function scopeBuscarUsuario($query, Request $request)
    {
        if ($request->has('buscar') && !is_null($request->get('buscar'))){
            $query->where('nombre', 'LIKE', "%{$request->get('buscar')}%")
                ->orWhere('apellido', 'LIKE', "%{$request->get('buscar')}%");
        }
        return $query;
    }

    /**
     * END SCOPES
     */

    /**
     * ACCESSORS AND MUTATORS
     */
    public function getFullNameAttribute()
    {
        return "{$this->nombre} {$this->apellido}";
    }


    /**
     * Send the password reset notification.
     *
     * @param string $token
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPassword($token, $this->email));
    }
}

app/Http/Controllers/Admin/PresupuestoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Empresa;
use App\FormaDePago;
use App\FormaPagoPrespuesto;
use App\Http\Controllers\Controller;
use App\Marca;
use App\Moneda;
use App\Notifications\EnviarPresupuesto;
use App\Presupuesto;
use App\PresupuestoProducto;
use App\Sucursal;
use Barryvdh\DomPDF\Facade;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Notification;

class PresupuestoController extends Controller
{
    public function listado(Request $request)
    {
        $presupuestos = Presupuesto::with("cliente", "productos")
            ->orderBy('created_at','DESC')
            ->paginate(20);

        return view('presupuestos.listado', compact('presupuestos'));
    }

    public function crear()
    {
        $monedas = Moneda::all();
        $formasPago = FormaDePago::all();
        $marcas = Marca::orderBy('nombre')->get();
        $sucursales = Empresa::all();

        return view('presupuestos.crear', compact('monedas', 'formasPago', 'marcas', 'sucursales'));
    }

    public function guardar(Request $request)
    {
        DB::beginTransaction();
        try {
            $pagos = collect($request->only('pagos')["pagos"]);

            $productos = $request->input('producto');

            $dataPresupuesto = $request->input('presupuesto');
            $dataPresupuesto["usuario_id"] = auth()->user()->id;
            $dataPresupuesto["monto"] = $productos["total"];
            unset($productos["total"]);
            $dataPresupuesto["sucursal_id"] = auth()->user()->sucursal->id;

            $presupuesto = Presupuesto::create($dataPresupuesto);

            $presupuesto->productos()->attach($productos);

            $presupuesto->formas_pago()->attach($pagos->toArray());

            DB::commit();
        }catch (\Exception $e) {
            DB::rollBack();
            return back()->withErrors($e->getMessage());
        }
        return redirect()->route("presupuestos.ver", $presupuesto)->with("success", "El presupuesto se creo con éxito");
    }

    public function ver(Presupuesto $presupuesto)
    {
        $presupuesto->load("cliente", "productos", "moneda");

        return view('presupuestos.ver', compact('presupuesto'));
    }

    public function editar(Presupuesto $presupuesto)
    {
        $monedas = Moneda::all();
        $formasPago = FormaDePago::all();
        $marcas = Marca::orderBy('nombre')->get();
        $presupuesto->load("cliente", "productos", "moneda");
        $otrasFormasPago = $presupuesto->formas_pago->where("id", "!=",3)->values();
        $cheques = $presupuesto->formas_pago->where("id", 3)->values();
        $sucursales = Empresa::all();

        return view('presupuestos.editar', compact('monedas', 'formasPago', 'marcas',
            'presupuesto','cheques', 'otrasFormasPago', 'sucursales'));
    }

    public function presupuesto(Presupuesto $presupuesto)
    {
        $pdf = $this->getPdf($presupuesto);

        return $pdf->stream('presupuesto.pdf');
    }

    public function enviarPdf(Presupuesto $presupuesto, Request $request)
    {
        $pdf = $this->getPdf($presupuesto);

        $data = $request->all();
        try {
            Mail::send([], [], function ($email) use ($pdf, $data) {
                $email->from(auth()->user()->email);
                $email->to($data["email"]);
                $email->subject("Presupuesto");
                $email->setBody('Adjuntamos prespuesto requerido');
                $email->setBody('Saludos!');
                $email->attachData($pdf->output(), "presupusto.pdf");
            });
        }catch (\Exception $e) {
            return back()->withErrors($e->getMessage());
        }

        return back()->with("success", "El correo fue enviado");
    }

    private function getPdf(Presupuesto $presupuesto)
    {
        $presupuesto->load("cliente", "productos", "moneda");

        $vista = view('presupuestos.template.presupuesto', compact('presupuesto'))->render();

        return Facade::loadHtml($vista);
    }
}

resources/views/presupuestos/template/presupuesto.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Presupuesto</title>

    <style type="text/css">
        body {
            font-size: 12px;
            font-family: "Helvetica Neue Light", "HelveticaNeue-Light", "Helvetica Neue", Calibri, Helvetica, Arial, sans-serif;
        }
        p{
            margin:0;
            padding:0;
        }
        .imgProducto {
            display: block;
            max-width:250px;
            max-height:110px;
            width: auto;
            height: auto;
            padding-top: 100px;
        }

        #productos {
            margin-top: 50px;
        }

        tr.border_bottom td {
            border-bottom:1pt solid black;
            margin-top: 100px;
        }
    </style>
</head>
<body>
    <table width="100%">
        <tr>
            <td valign="left" width="5%">
                <img src="{{public_path('images/logo-horizontal.png')}}" alt="" width="150" style="margin: 0"/>
            </td>


            <td width="100%" align="right">
                <h3 style="margin-top: 0px;">{{ $presupuesto->empresa->nombre }}</h3>

                    <strong>CUIT: {{ $presupuesto->empresa->cuit }}</strong>
                    <p>{{ $presupuesto->empresa->direccion }}</p>
                    <p>Tel {{ $presupuesto->sucursal->telefono }}</p>
                    <p>{{ $presupuesto->sucursal->email }}</p>

            </td>
        </tr>
    </table>

    <table width="100%" style="border-top: 2px solid black;">
        <tr>
            <td align="left">
                <strong>Sres. {{ $presupuesto->cliente->razon_social }}</strong>
            </td>
            <td align="right">
                <strong>Santiago del estero, {{ \Carbon\Carbon::now()->day }} de {{ \Carbon\Carbon::now()->monthName }} de {{ \Carbon\Carbon::now()->year }}</strong>
            </td>
        </tr>
        <tr>
            <td align="left">
                <a href="mailto:{{ $presupuesto->cliente->email }}">{{ $presupuesto->cliente->email }}</a>
                <div><strong>{{ $presupuesto->cliente->telefono }}</strong></div>
                <div>Atte.</div>

            </td>
            <td align="right">
                Cotizacion Nº {{ $presupuesto->nro_cotizacion }}
            </td>
        </tr>
    </table>

    <br>


        @foreach($presupuesto->productos as $producto)
            <div style="clear: left">

                <div style="float:left; width: 450px">
                        <div><strong>{{ $producto->producto_completo }}</strong></div>
                        <div>
                            <strong>
                                PRECIO: {{ $producto->pivot->cantidad }} X {{ $producto->pivot->moneda->simbolo }} {{ number_format($producto->pivot->subtotal, 2, ",", ".") }} ({{ $presupuesto->iva =='con_iva' ? 'IVA Incluido' : 'Sin IVA' }})
                            </strong>
                        </div>
                        <div>
                            {!! $producto->descripcion !!}
                        </div>
                    </div>

                @if($producto->imagen()->exists())
                    <div style="float:left; height: 120px; width: 200px">
                        <img style="margin-top: -100px" src="{{ public_path('images/productos') }}/{{$producto->imagen->nombre}}" class="imgProducto" alt="">
                    </div>
                @endif
            </div>
            <hr style="clear: left; border: 0.5px solid black;">
        @endforeach


{{--    <table width="100%">--}}
{{--        @foreach($presupuesto->productos as $producto)--}}
{{--            <tr class="border_bottom">--}}
{{--                <td style="padding-bottom: 20px">--}}
{{--                    <div><strong>{{ $producto->producto_completo }}</strong></div>--}}
{{--                    <div>--}}
{{--                        <strong>--}}
{{--                            PRECIO: {{ $producto->pivot->moneda->simbolo }} {{ $producto->pivot->precio }} ({{ $presupuesto->iva =='con_iva' ? 'IVA Incluido' : 'Sin IVA' }})--}}
{{--                        </strong>--}}
{{--                    </div>--}}
{{--                    <div>--}}
{{--                        {!! $producto->descripcion !!}--}}
{{--                    </div>--}}
{{--                </td>--}}

{{--                @if($producto->imagen()->exists())--}}
{{--                    <td align="center" >--}}
{{--                        <img style="margin-top: -100px" src="{{ public_path('images/productos') }}/{{$producto->imagen->nombre}}" class="imgProducto" alt="">--}}
{{--                    </td>--}}
{{--                @endif--}}
{{--            </tr>--}}
{{--        @endforeach--}}
{{--    </table>--}}
    <br>
    <h4 align="center">CONDICIONES GENERALES</h4>
    <br>
    <div><strong>VALIDEZ DE LA OFERTA: </strong>{{ $presupuesto->validez }} días corridos.</div>
    <div><strong>PLAZO DE ENTREGA: </strong>{{ $presupuesto->plazo_entrega == 0 ? 'Inmediata' : $presupuesto->plazo_entrega . " días" }}.</div>
    <div><strong>FORMA DE PAGO</strong></div>
    <table width="100%" border="1">
        <thead style="background-color: lightgray;">
        <tr>
            <th>Forma de pago</th>
            <th>Monto</th>
            <th>Fecha</th>
        </tr>
        </thead>
        <tbody>
        @foreach($presupuesto->formas_pago as $formaPago)
            <tr>
                <td align="center">{{ $formaPago->nombre }}</td>
                <td align="right">{{ optional($formaPago->pivot->moneda)->simbolo }} {{ number_format($formaPago->pivot->monto, 2, ",",".") }}</td>
                <td align="right">{{ !is_null($formaPago->pivot->fecha) ? $formaPago->pivot->fecha->format("d/m/Y") : '-----------------' }}</td>
            </tr>
        @endforeach
        </tbody>
        <tfoot style="background-color: lightgray;">
        <tr>
            <td align="center"><strong>TOTAL</strong></td>
            <td align="right">{{ $presupuesto->monto }}</td>
            <td></td>
        </tr>
        </tfoot>
    </table>

    <br>

    <span>Sin otro particular, saludamos a Uds., muy atentamente</span>

    <br><br>

    <table width="100%">
        <tr>
            <td width="100%">
            </td>
            <td width="100%">
            </td>
            <td width="100%">
                <div align="center">
                    <strong>{{ $presupuesto->usuario->full_name }}</strong>
                </div>
            </td>
        </tr>
        <tr>
            <td width="100%"></td>
            <td width="100%"></td>
            <td width="100%">
                <div align="center">
                    Correo: <a href="mailto:{{ $presupuesto->usuario->email }}">{{ $presupuesto->usuario->email }}</a>
                </div>
            </td>
        </tr>
        <tr>
            <td width="100%"></td>
            <td width="100%"></td>
            <td width="100%">
                <div align="center">
                    <a href="https://www.robertochelala.com.ar/">www.robertochelala.com.ar</a>
                </div>
            </td>
        </tr>
    </table>
    <script type="text/php">
        if ( isset($pdf) ) {
            $pdf->page_script('
                $font = $fontMetrics->get_font("Arial, Helvetica, sans-serif", "normal");
                $pdf->text(270, 810, "Pagina $PAGE_NUM de $PAGE_COUNT", $font, 10);
            ');
        }
    </script>
</body>
</html>